In [1]:
import pandas as pd
import numpy as np

In [2]:
new_2020 = pd.read_excel('Table_6_03_Aug2020.xlsx', skiprows=1 )
#Table_6_03 available at https://www.eia.gov/electricity/monthly/ (August 2020 release)
new_2020.head()

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
0,2020,1.0,61012.0,AES Distributed Energy,IPP,AES Tonawanda Solar LLC,NY,63161.0,TNWDA,2.0,Solar Photovoltaic,SUN,PV
1,2020,1.0,63115.0,"AZ Solar 1, LLC",IPP,OE_AZ1,AZ,63349.0,AZ1,32.5,Solar Photovoltaic,SUN,PV
2,2020,1.0,63049.0,Cannon Garden LLC,IPP,Cannon Garden Solar,MN,63252.0,CGS,1.0,Solar Photovoltaic,SUN,PV
3,2020,1.0,63120.0,"Cubera Solar, LLC",IPP,"Cubera Solar, LLC",NC,63346.0,PGR06,2.0,Solar Photovoltaic,SUN,PV
4,2020,1.0,62801.0,DG Linden New Jersey LLC,IPP,DG Infineum,NJ,62958.0,INFNM,2.0,Solar Photovoltaic,SUN,PV

In [8]:
planned = pd.read_excel('Table_6_05_Aug2020.xlsx', skiprows=1 )
#Table_6_05 available at https://www.eia.gov/electricity/monthly/ (August 2020 release)
planned_2020 = planned[planned['Year'] == 2020]
planned_2020.head()

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code,Status,Nameplate Capacity (MW)
0,2020,7.0,61012.0,AES Distributed Energy,IPP,Allis Medina Solar LLC,NY,63129.0,ALLIS,5,Solar Photovoltaic,SUN,PV,"(TS) Construction complete, but not yet in com...",5.0
1,2020,7.0,61012.0,AES Distributed Energy,IPP,"Cronin Road Solar 1, LLC CSG",MA,63011.0,BESS,1.5,Batteries,MWH,BA,"(TS) Construction complete, but not yet in com...",1.5
2,2020,7.0,61012.0,AES Distributed Energy,IPP,"Finchville Solar, LLC",NY,62999.0,FINCH,5,Solar Photovoltaic,SUN,PV,"(TS) Construction complete, but not yet in com...",5.0
3,2020,7.0,61012.0,AES Distributed Energy,IPP,Lane Ave Solar LLC,MA,63041.0,HANRA,1.5,Solar Photovoltaic,SUN,PV,"(TS) Construction complete, but not yet in com...",1.5
4,2020,7.0,61012.0,AES Distributed Energy,IPP,Randall Solar Project Hybrid,MA,63475.0,BATT,3.3,Batteries,MWH,BA,"(TS) Construction complete, but not yet in com...",3.3

In [7]:
cols_list = planned_2020.columns.tolist()
cols_list

['Year',
 'Month',
 'Entity ID',
 'Entity Name',
 'Plant Producer Type',
 'Plant Name',
 'Plant State',
 'Plant ID',
 'Generator ID',
 '\nNet Summer Capacity (MW)',
 'Technology',
 'Energy Source Code',
 'Prime Mover Code',
 'Status',
 '\nNameplate Capacity (MW)']

In [12]:
all_2020 = pd.concat([new_2020, planned_2020])
all_2020 = all_2020[cols_list]
all_2020.head()

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code,Status,Nameplate Capacity (MW)
0,2020,1.0,61012.0,AES Distributed Energy,IPP,AES Tonawanda Solar LLC,NY,63161.0,TNWDA,2,Solar Photovoltaic,SUN,PV,NaN,NaN
1,2020,1.0,63115.0,"AZ Solar 1, LLC",IPP,OE_AZ1,AZ,63349.0,AZ1,32.5,Solar Photovoltaic,SUN,PV,NaN,NaN
2,2020,1.0,63049.0,Cannon Garden LLC,IPP,Cannon Garden Solar,MN,63252.0,CGS,1,Solar Photovoltaic,SUN,PV,NaN,NaN
3,2020,1.0,63120.0,"Cubera Solar, LLC",IPP,"Cubera Solar, LLC",NC,63346.0,PGR06,2,Solar Photovoltaic,SUN,PV,NaN,NaN
4,2020,1.0,62801.0,DG Linden New Jersey LLC,IPP,DG Infineum,NJ,62958.0,INFNM,2,Solar Photovoltaic,SUN,PV,NaN,NaN

In [13]:
new_2020.shape, planned_2020.shape, all_2020.shape

((257, 13), (527, 15), (784, 15))

In [14]:
NY_2020 = all_2020[all_2020['Plant State'] =='NY']
NY_2020.shape

(58, 15)

In [17]:
NY_2020.groupby('Technology')['\nNet Summer Capacity (MW)'].sum()

Technology
Batteries                             29.9
Natural Gas Fired Combined Cycle    1016.1
Onshore Wind Turbine                 204.0
Petroleum Liquids                      1.5
Solar Photovoltaic                   115.4
Name: \nNet Summer Capacity (MW), dtype: float64

In [15]:
IA_2020 = all_2020[all_2020['Plant State'] =='IA']
IA_2020.shape

(20, 15)

In [16]:
IA_2020.groupby('Technology')['\nNet Summer Capacity (MW)'].sum()

Technology
Conventional Hydroelectric      55.0
Onshore Wind Turbine          1753.7
Petroleum Liquids                6.7
Solar Photovoltaic             102.6
Name: \nNet Summer Capacity (MW), dtype: float64

In [105]:
inact = pd.read_excel('Table_6_04_Aug2020.xlsx', skiprows=1)
#Table_6_04 available at https://www.eia.gov/electricity/monthly/ (August 2020 release)
inact.head()

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
0,2020,1.0,3046.0,Duke Energy Progress - (NC),Electric Utility,Asheville,NC,2706.0,1,189.0,Conventional Steam Coal,BIT,ST
1,2020,1.0,3046.0,Duke Energy Progress - (NC),Electric Utility,Asheville,NC,2706.0,2,189.0,Conventional Steam Coal,BIT,ST
2,2020,1.0,9155.0,Inland Empire Energy Ctr LLC,IPP,Inland Empire Energy Center,CA,55853.0,1,345.0,Natural Gas Fired Combined Cycle,NG,CS
3,2020,1.0,9155.0,Inland Empire Energy Ctr LLC,IPP,Inland Empire Energy Center,CA,55853.0,2,345.0,Natural Gas Fired Combined Cycle,NG,CS
4,2020,1.0,15298.0,Talen Montana LLC,IPP,Colstrip,MT,6076.0,1,307.0,Conventional Steam Coal,SUB,ST

In [106]:
inact[inact['Plant State']=='NY']

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
35,2020,3.0,22129.0,Somerset Operating Co LLC,IPP,Somerset Operating Co LLC,NY,6082.0,1,685.9,Conventional Steam Coal,BIT,ST
37,2020,4.0,6027.0,Entergy Nuclear Indian Point 2,IPP,Indian Point 2,NY,2497.0,2,1016.1,Nuclear,NUC,ST

In [110]:
inact[inact['Plant State']=='MT']

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
4,2020,1.0,15298.0,Talen Montana LLC,IPP,Colstrip,MT,6076.0,1,307.0,Conventional Steam Coal,SUB,ST
5,2020,1.0,15298.0,Talen Montana LLC,IPP,Colstrip,MT,6076.0,2,307.0,Conventional Steam Coal,SUB,ST

In [107]:
planned_inact = pd.read_excel('Table_6_06_Aug2020.xlsx', skiprows=1)
#Table_6_06 available at https://www.eia.gov/electricity/monthly/ (August 2020 release)
planned_inact.head()

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
0,2020,7,2848.0,California Institute-Technology,Commercial,California Institute of Technology,CA,10262.0,GEN6,9.0,Natural Gas Fired Combined Cycle,NG,CT
1,2020,7,13756.0,Northern Indiana Pub Serv Co,Electric Utility,Bailly,IN,995.0,10,31.0,Natural Gas Fired Combustion Turbine,NG,GT
2,2020,7,20737.0,Willmar Municipal Utilities,Electric Utility,Willmar,MN,2022.0,3,16.8,Natural Gas Steam Turbine,NG,ST
3,2020,7,20737.0,Willmar Municipal Utilities,Electric Utility,Willmar,MN,2022.0,ST2,6.5,Natural Gas Steam Turbine,NG,ST
4,2020,8,11713.0,City of Marshall - (MI),Electric Utility,Marshall (MI),MI,1844.0,IC2,0.9,Natural Gas Internal Combustion Engine,NG,IC

In [109]:
planned_inact[planned_inact['Technology']=='Nuclear']

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
46,2020,12,55269.0,NextEra Energy Duane Arnold LLC,IPP,Duane Arnold Energy Center,IA,1060.0,1,601.4,Nuclear,NUC,ST
63,2021,4,6028.0,Entergy Nuclear Indian Point 3,IPP,Indian Point 3,NY,8907.0,3,1037.9,Nuclear,NUC,ST
114,2022,6,56192.0,Entergy Nuclear Palisades LLC,IPP,Palisades,MI,1715.0,1,771.6,Nuclear,NUC,ST
229,2024,11,14328.0,Pacific Gas & Electric Co.,Electric Utility,Diablo Canyon,CA,6099.0,1,1122.0,Nuclear,NUC,ST
283,2025,8,14328.0,Pacific Gas & Electric Co.,Electric Utility,Diablo Canyon,CA,6099.0,2,1118.0,Nuclear,NUC,ST

In [111]:
planned_inact[planned_inact['Plant State']=='WA']

,Year,Month,Entity ID,Entity Name,Plant Producer Type,Plant Name,Plant State,Plant ID,Generator ID,Net Summer Capacity (MW),Technology,Energy Source Code,Prime Mover Code
45,2020,12,58341.0,McKinley Paper Co. - Washington Mill,Industrial,McKinley Paper Co. - Washington Mill,WA,58352.0,G-11,20.0,Wood/Wood Waste Biomass,WDS,ST
49,2020,12,19099.0,TransAlta Centralia Gen LLC,IPP,Transalta Centralia Generation,WA,3845.0,1,670.0,Conventional Steam Coal,RC,ST
304,2025,12,19099.0,TransAlta Centralia Gen LLC,IPP,Transalta Centralia Generation,WA,3845.0,2,670.0,Conventional Steam Coal,RC,ST

In [23]:
existing_plants = pd.read_excel('3_1_Generator_Y2019_Early_Release.xlsx', skiprows=2 )
#from https://www.eia.gov/electricity/data/eia860/
existing_plants.shape

(22701, 73)

In [24]:
existing_plants.head()

,Utility ID,Utility Name,Plant Code,Plant Name,State,County,Generator ID,Technology,Prime Mover,Unit Code,...,Planned Energy Source 1,Planned New Nameplate Capacity (MW),Planned Repower Month,Planned Repower Year,Other Planned Modifications?,Other Modifications Month,Other Modifications Year,Multiple Fuels?,Cofire Fuels?,Switch Between Oil and Natural Gas?
0,195,Alabama Power Co,2,Bankhead Dam,AL,Tuscaloosa,1,Conventional Hydroelectric,HY,NaN,...,NaN,,,,NaN,,,N,NaN,NaN
1,195,Alabama Power Co,3,Barry,AL,Mobile,1,Natural Gas Steam Turbine,ST,NaN,...,NaN,,,,NaN,,,N,N,NaN
2,195,Alabama Power Co,3,Barry,AL,Mobile,2,Natural Gas Steam Turbine,ST,NaN,...,NaN,,,,NaN,,,N,NaN,NaN
3,195,Alabama Power Co,3,Barry,AL,Mobile,4,Conventional Steam Coal,ST,NaN,...,NaN,,,,NaN,,,N,NaN,NaN
4,195,Alabama Power Co,3,Barry,AL,Mobile,5,Conventional Steam Coal,ST,NaN,...,NaN,,,,NaN,,,N,NaN,NaN

In [25]:
existing_plants.columns

Index(['Utility ID', 'Utility Name', 'Plant Code', 'Plant Name', 'State',
       'County', 'Generator ID', 'Technology', 'Prime Mover', 'Unit Code',
       'Ownership', 'Duct Burners',
       'Can Bypass Heat Recovery Steam Generator?',
       'RTO/ISO LMP Node Designation',
       'RTO/ISO Location Designation for Reporting Wholesale Sales Data to FERC',
       'Nameplate Capacity (MW)', 'Nameplate Power Factor',
       'Summer Capacity (MW)', 'Winter Capacity (MW)', 'Minimum Load (MW)',
       'Uprate or Derate Completed During Year',
       'Month Uprate or Derate Completed', 'Year Uprate or Derate Completed',
       'Status', 'Synchronized to Transmission Grid', 'Operating Month',
       'Operating Year', 'Planned Retirement Month', 'Planned Retirement Year',
       'Associated with Combined Heat and Power System', 'Sector Name',
       'Sector', 'Topping or Bottoming', 'Energy Source 1', 'Energy Source 2',
       'Energy Source 3', 'Energy Source 4', 'Energy Source 5',
       'Energy Source 6', 'Startup Source 1', 'Startup Source 2',
       'Startup Source 3', 'Startup Source 4',
       'Solid Fuel Gasification System?', 'Carbon Capture Technology?',
       'Turbines or Hydrokinetic Buoys',
       'Time from Cold Shutdown to Full Load', 'Fluidized Bed Technology?',
       'Pulverized Coal Technology?', 'Stoker Technology?',
       'Other Combustion Technology?', 'Subcritical Technology?',
       'Supercritical Technology?', 'Ultrasupercritical Technology?',
       'Planned Net Summer Capacity Uprate (MW)',
       'Planned Net Winter Capacity Uprate (MW)', 'Planned Uprate Month',
       'Planned Uprate Year', 'Planned Net Summer Capacity Derate (MW)',
       'Planned Net Winter Capacity Derate (MW)', 'Planned Derate Month',
       'Planned Derate Year', 'Planned New Prime Mover',
       'Planned Energy Source 1', 'Planned New Nameplate Capacity (MW)',
       'Planned Repower Month', 'Planned Repower Year',
       'Other Planned Modifications?', 'Other Modifications Month',
       'Other Modifications Year', 'Multiple Fuels?', 'Cofire Fuels?',
       'Switch Between Oil and Natural Gas?'],
      dtype='object')

In [26]:
state_list = existing_plants.State.unique().tolist()
len(state_list)

51

In [27]:
existing_plants.Technology.unique()

array(['Conventional Hydroelectric', 'Natural Gas Steam Turbine',
       'Conventional Steam Coal', 'Natural Gas Fired Combined Cycle',
       'Natural Gas Fired Combustion Turbine', 'Petroleum Liquids',
       'Natural Gas Internal Combustion Engine', 'Nuclear',
       'Onshore Wind Turbine', 'Solar Photovoltaic',
       'Hydroelectric Pumped Storage', 'Geothermal', 'Landfill Gas',
       'Batteries', 'Wood/Wood Waste Biomass',
       'Coal Integrated Gasification Combined Cycle', 'Other Gases',
       'Petroleum Coke', 'Municipal Solid Waste',
       'Natural Gas with Compressed Air Storage', 'All Other',
       'Other Waste Biomass', 'Solar Thermal without Energy Storage',
       'Other Natural Gas', 'Solar Thermal with Energy Storage',
       'Flywheels', 'Offshore Wind Turbine'], dtype=object)

In [29]:
coal = existing_plants[existing_plants['Technology'] == 'Conventional Steam Coal']
coal.shape

(666, 73)

In [31]:
coal_states = coal.State.unique().tolist()
len(coal_states)

46

Four states (plus DC) have no coal plants as of end of 2019.

In [33]:
np.setdiff1d(state_list, coal_states)

array(['DC', 'MA', 'ME', 'RI', 'VT'],
      dtype='<U2')

In [92]:
coal_plants = coal.groupby('State')['Plant Name'].value_counts()
coal_plants

State  Plant Name
AK     Eielson AFB Central Heat & Power Plant    5
       Utility Plants Section                    4
       Aurora Energy LLC Chena                   3
       University of Alaska Fairbanks            3
       Healy                                     2
AL     James H Miller Jr                         4
       Charles R Lowman                          3
       Barry                                     2
       E C Gaston                                1
AR     Independence Steam Electric Station       2
       White Bluff                               2
       Flint Creek                               1
       John W Turk Jr Power Plant                1
       Plum Point Energy Station                 1
AZ     Springerville                             4
       Cholla                                    3
       Coronado                                  2
       Apache Station                            1
CA     Argus Cogen Plant                         3
CO     Comanche (CO)                             3
       Craig (CO)                                3
       Hayden                                    2
       Martin Drake                              2
       Pawnee                                    1
       Rawhide                                   1
       Ray D Nixon                               1
       Western Sugar Coop- Ft Morgan             1
CT     Bridgeport Station                        1
DE     Indian River Generating Station           1
FL     Big Bend                                  4
                                                ..
WI     Columbia (WI)                             2
       Elm Road Generating Station               2
       Weston                                    2
       Edgewater                                 1
       Genoa                                     1
       John P Madgett                            1
       Kaukauna Paper Mill                       1
       Rhinelander Mill                          1
WV     FirstEnergy Harrison Power Station        3
       John E Amos                               3
       Mt Storm                                  3
       FirstEnergy Fort Martin Power Station     2
       FirstEnergy Pleasants Power Station       2
       Mitchell (WV)                             2
       Grant Town Power Plant                    1
       Longview Power Plant                      1
       Morgantown Energy Facility                1
       Mountaineer                               1
WY     Genesis Alkali                            6
       Dave Johnston                             4
       Jim Bridger                               4
       Laramie River Station                     3
       Naughton                                  3
       General Chemical                          2
       Dry Fork Station                          1
       Neil Simpson II                           1
       Wygen 1                                   1
       Wygen 2                                   1
       Wygen III                                 1
       Wyodak                                    1
Name: Plant Name, Length: 307, dtype: int64

In [91]:
hs['NY'].index.tolist()

['RED-Rochester, LLC', 'Dunkirk Generating Plant', 'Somerset Operating Co LLC']

In [94]:
coal_counter = {}
for i in coal_states:
    coal_counter[i] = len(coal_plants[i])

coal_counter

{'AK': 5,
 'AL': 4,
 'AR': 5,
 'AZ': 4,
 'CA': 1,
 'CO': 8,
 'CT': 1,
 'DE': 1,
 'FL': 9,
 'GA': 3,
 'HI': 1,
 'IA': 14,
 'ID': 1,
 'IL': 15,
 'IN': 15,
 'KS': 5,
 'KY': 14,
 'LA': 4,
 'MD': 6,
 'MI': 13,
 'MN': 12,
 'MO': 11,
 'MS': 2,
 'MT': 6,
 'NC': 9,
 'ND': 9,
 'NE': 10,
 'NH': 2,
 'NJ': 2,
 'NM': 3,
 'NV': 2,
 'NY': 3,
 'OH': 12,
 'OK': 6,
 'OR': 1,
 'PA': 18,
 'SC': 4,
 'SD': 1,
 'TN': 5,
 'TX': 16,
 'UT': 5,
 'VA': 6,
 'WA': 1,
 'WI': 10,
 'WV': 10,
 'WY': 12}

States with only a single coal generating station

In [100]:
singles = []

for key in coal_counter:
    if coal_counter[key] == 1:
        singles.append(key)
        
for i in singles:
    print(i, coal_plants[i].index[0])

SD Big Stone
CT Bridgeport Station
DE Indian River Generating Station
ID Amalgamated Sugar Twin Falls
WA Transalta Centralia Generation
CA Argus Cogen Plant
OR Boardman
HI AES Hawaii